<?php

namespace Database\Seeders;

use App\Models\NotificationSetting;
use Illuminate\Database\Seeder;

class NotificationSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // ==========================================
            // 1. TAHAPAN ALUR ORDER (17 TAHAPAN)
            // ==========================================
            [
                'event_key' => 'stage_survey',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Penugasan Survey',
                'deskripsi' => 'Notifikasi saat order dibuat dan tim survey ditugaskan',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [4, 5], // Surveyor, Drafter
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9], // KM, PM, SPV
                'days_offset' => 0,
                'title_template' => 'Survey Request - {nama_project}',
                'message_template' => 'Anda ditugaskan untuk melakukan survey pada project "{nama_project}". Silakan lengkapi data survey.',
                'action_url' => '/survey-results',
                'available_placeholders' => ['{nama_project}', '{customer_name}', '{tanggal_survey}'],
            ],
            [
                'event_key' => 'stage_moodboard',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Permintaan Moodboard',
                'deskripsi' => 'Notifikasi setelah survey selesai untuk desainer membuat konsep moodboard',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [7], // Desainer
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Moodboard Request - {nama_project}',
                'message_template' => 'Survey telah selesai untuk project "{nama_project}". Silakan buat moodboard.',
                'action_url' => '/moodboard',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_estimasi',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Permintaan Estimasi Biaya',
                'deskripsi' => 'Notifikasi setelah moodboard selesai untuk tim estimator menghitung estimasi',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'all_by_role',
                'target_role_ids' => [6], // Estimator
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Estimasi Request - {nama_project}',
                'message_template' => 'Moodboard telah selesai untuk project "{nama_project}". Silakan buat estimasi.',
                'action_url' => '/estimasi',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_commitment_fee',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Permintaan Commitment Fee (CF)',
                'deskripsi' => 'Notifikasi setelah moodboard kasar disetujui untuk pengisian commitment fee',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'all_by_role',
                'target_role_ids' => [2], // Legal Admin
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Commitment Fee Request - {nama_project}',
                'message_template' => 'Moodboard kasar telah di-approve untuk project "{nama_project}". Silakan isi commitment fee.',
                'action_url' => '/commitment-fee',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_design_approval',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Approval Desain',
                'deskripsi' => 'Notifikasi saat estimasi selesai untuk review dan approval desain',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [7], // Desainer
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Design Approval - {nama_project}',
                'message_template' => 'Estimasi telah selesai untuk project "{nama_project}". Silakan review dan approve design.',
                'action_url' => '/moodboard',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_final_design',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Permintaan Desain Final',
                'deskripsi' => 'Notifikasi untuk desainer membuat desain final 3D / detail',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [7], // Desainer
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Final Design Request - {nama_project}',
                'message_template' => 'Commitment fee telah disetujui untuk project "{nama_project}". Silakan buat final design.',
                'action_url' => '/desain-final',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_item_pekerjaan',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Permintaan Item Pekerjaan',
                'deskripsi' => 'Notifikasi setelah desain final selesai untuk penyusunan rincian item pekerjaan',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [6, 10], // Estimator, PM
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Item Pekerjaan Request - {nama_project}',
                'message_template' => 'Final design telah disetujui untuk project "{nama_project}". Silakan buat item pekerjaan.',
                'action_url' => '/item-pekerjaan',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_rab_internal',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Permintaan RAB Internal',
                'deskripsi' => 'Notifikasi untuk penyusunan RAB internal oleh estimator',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'all_by_role',
                'target_role_ids' => [6], // Estimator
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'RAB Internal Request - {nama_project}',
                'message_template' => 'Item pekerjaan telah selesai untuk project "{nama_project}". Silakan buat RAB internal.',
                'action_url' => '/rab-internal',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_kontrak',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Permintaan Pembuatan Kontrak',
                'deskripsi' => 'Notifikasi ke legal admin saat RAB disetujui untuk pembuatan kontrak kerja',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'all_by_role',
                'target_role_ids' => [2], // Legal Admin
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Kontrak Request - {nama_project}',
                'message_template' => 'RAB internal telah disetujui untuk project "{nama_project}". Silakan buat kontrak.',
                'action_url' => '/kontrak',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_invoice',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Permintaan Invoice & Penagihan',
                'deskripsi' => 'Notifikasi setelah kontrak ditandatangani untuk penerbitan invoice pembayaran',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'all_by_role',
                'target_role_ids' => [2], // Legal Admin / Finance
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Invoice Request - {nama_project}',
                'message_template' => 'Kontrak telah disetujui untuk project "{nama_project}". Silakan buat invoice.',
                'action_url' => '/invoice',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_survey_schedule',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Jadwal Survey Lanjutan',
                'deskripsi' => 'Notifikasi jadwal survey lanjutan setelah kontrak ditandatangani',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [5, 4], // Drafter, Surveyor
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Jadwal Survey Request - {nama_project}',
                'message_template' => 'Kontrak telah disetujui untuk project "{nama_project}". Silakan atur jadwal survey.',
                'action_url' => '/survey-schedule',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_survey_ulang',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Permintaan Survey Ulang',
                'deskripsi' => 'Notifikasi saat diperlukan survey ulang di lapangan',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [4, 5], // Surveyor, Drafter
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Survey Ulang Request - {nama_project}',
                'message_template' => 'Perlu survey ulang untuk project "{nama_project}". Silakan lakukan survey ulang.',
                'action_url' => '/survey-ulang',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_gambar_kerja',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Permintaan Gambar Kerja',
                'deskripsi' => 'Notifikasi untuk drafter menyelesaikan gambar kerja teknik',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [5], // Drafter
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Gambar Kerja Request - {nama_project}',
                'message_template' => 'Survey telah selesai untuk project "{nama_project}". Silakan buat gambar kerja.',
                'action_url' => '/gambar-kerja',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_meeting_vendor',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Jadwal Meeting Vendor',
                'deskripsi' => 'Notifikasi meeting koordinasi vendor setelah gambar kerja disetujui',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'all_by_role',
                'target_role_ids' => [6, 10], // Estimator, PM
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Meeting Vendor Request - {nama_project}',
                'message_template' => 'Gambar kerja telah disetujui untuk project "{nama_project}". Silakan jadwalkan meeting vendor.',
                'action_url' => '/meeting-vendor',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_approval_material',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Approval Material Proyek',
                'deskripsi' => 'Notifikasi persetujuan material proyek setelah meeting vendor',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [10, 7], // PM, Desainer
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Approval Material Request - {nama_project}',
                'message_template' => 'Meeting vendor telah selesai untuk project "{nama_project}". Silakan lakukan approval material.',
                'action_url' => '/approval-material',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_workplan',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Penyusunan Workplan',
                'deskripsi' => 'Notifikasi untuk menyusun timeline workplan pekerjaan proyek',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [10, 9], // PM, Supervisor
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Workplan Request - {nama_project}',
                'message_template' => 'Material telah di-approve untuk project "{nama_project}". Silakan buat workplan.',
                'action_url' => '/workplan',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],
            [
                'event_key' => 'stage_project_management',
                'category' => 'order_stage',
                'nama_pengaturan' => 'Produksi & Manajemen Proyek',
                'deskripsi' => 'Notifikasi mulainya fase produksi dan pengawasan lapangan',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [10, 9], // PM, Supervisor
                'send_to_management' => true,
                'management_role_ids' => [11, 10, 9],
                'days_offset' => 0,
                'title_template' => 'Project Management Request - {nama_project}',
                'message_template' => 'Workplan telah selesai untuk project "{nama_project}". Silakan mulai project management.',
                'action_url' => '/project-management',
                'available_placeholders' => ['{nama_project}', '{customer_name}'],
            ],

            // ==========================================
            // 2. MODUL PENGINGAT OTOMATIS (REMINDERS)
            // ==========================================
            [
                'event_key' => 'reminder_task_deadline',
                'category' => 'reminder',
                'nama_pengaturan' => 'Pengingat Deadline Tugas (H-X)',
                'deskripsi' => 'Pengingat otomatis sebelum batas waktu pengerjaan tugas berakhir',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'order_team',
                'target_role_ids' => [4, 5, 6, 7, 2, 10, 9],
                'send_to_management' => false,
                'management_role_ids' => [],
                'days_offset' => 1, // H-1
                'title_template' => 'Reminder: {tahap} - {nama_project}',
                'message_template' => 'Deadline {tahap} untuk project "{nama_project}" jatuh tempo {status_waktu}. Segera {status_aksi}.',
                'action_url' => '/order',
                'available_placeholders' => ['{tahap}', '{nama_project}', '{customer_name}', '{deadline}', '{status_waktu}', '{status_aksi}'],
            ],
            [
                'event_key' => 'reminder_payment_h_min',
                'category' => 'reminder',
                'nama_pengaturan' => 'Pengingat Jatuh Tempo Pembayaran Vendor (H-X)',
                'deskripsi' => 'Peringatan awal beberapa hari sebelum jatuh tempo pembayaran vendor/termin',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'all_by_role',
                'target_role_ids' => [2], // Legal Admin
                'send_to_management' => false,
                'management_role_ids' => [],
                'days_offset' => 7, // H-7
                'title_template' => '⚠️ Reminder Pembayaran H-{days_offset} - {nama_project}',
                'message_template' => 'Pembayaran {payment_type} untuk "{vendor_label}" sebesar {nominal} pada project "{nama_project}" akan jatuh tempo dalam {days_offset} hari ({tanggal_jatuh_tempo}).',
                'action_url' => '/cashflow-manual',
                'available_placeholders' => ['{payment_type}', '{vendor_label}', '{nominal}', '{nama_project}', '{days_offset}', '{tanggal_jatuh_tempo}'],
            ],
            [
                'event_key' => 'reminder_payment_due',
                'category' => 'reminder',
                'nama_pengaturan' => 'Pengingat Hari-H Pembayaran Vendor (H-0)',
                'deskripsi' => 'Pengingat saat pembayaran vendor/termin jatuh tempo pada hari ini',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'all_by_role',
                'target_role_ids' => [2], // Legal Admin
                'send_to_management' => false,
                'management_role_ids' => [],
                'days_offset' => 0,
                'title_template' => '💰 Reminder Pembayaran - {nama_project}',
                'message_template' => 'Pembayaran {payment_type} untuk "{vendor_label}" sebesar {nominal} pada project "{nama_project}" jatuh tempo hari ini.',
                'action_url' => '/cashflow-manual',
                'available_placeholders' => ['{payment_type}', '{vendor_label}', '{nominal}', '{nama_project}'],
            ],
            [
                'event_key' => 'reminder_material_fee',
                'category' => 'reminder',
                'nama_pengaturan' => 'Pengingat Pencairan Fee Vendor Material (H+X)',
                'deskripsi' => 'Pengingat pencairan fee vendor setelah approval material disetujui',
                'is_active' => true,
                'send_database' => true,
                'send_fcm' => true,
                'recipient_type' => 'all_by_role',
                'target_role_ids' => [2], // Legal Admin
                'send_to_management' => false,
                'management_role_ids' => [],
                'days_offset' => 3, // H+3
                'title_template' => '💸 Reminder Fee Vendor - {nama_project}',
                'message_template' => 'Material telah disetujui {days_offset} hari lalu untuk project "{nama_project}". Silakan proses pembayaran fee vendor.',
                'action_url' => '/cashflow-manual',
                'available_placeholders' => ['{nama_project}', '{customer_name}', '{days_offset}'],
            ],
        ];

        foreach ($settings as $setting) {
            NotificationSetting::updateOrCreate(
                ['event_key' => $setting['event_key']],
                $setting
            );
        }
    }
}
